USE [D0004N]
GO

/****** Object:  Table [dbo].[Bil]    Script Date: 2025-03-12 13:44:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Bil](
	[RegNr] [nchar](6) NOT NULL,
	[BilTyp] [int] NOT NULL,
 CONSTRAINT [PK_Bil] PRIMARY KEY CLUSTERED 
(
	[RegNr] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Bil]  WITH CHECK ADD  CONSTRAINT [FK_Bil_BilStation] FOREIGN KEY([RegNr])
REFERENCES [dbo].[BilStation] ([RegNr])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Bil] CHECK CONSTRAINT [FK_Bil_BilStation]
GO

ALTER TABLE [dbo].[Bil]  WITH CHECK ADD  CONSTRAINT [FK_Bil_BilTyp] FOREIGN KEY([BilTyp])
REFERENCES [dbo].[BilTyp] ([BilTyp])
GO

ALTER TABLE [dbo].[Bil] CHECK CONSTRAINT [FK_Bil_BilTyp]
GO

